config/routes.rb
# encoding: utf-8
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, skip: %i[registrations invitations]
end

app/models/application_record.rb
# encoding: utf-8
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# encoding: utf-8
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable, :lockable, :timeoutable, :invitable
end

app/controllers/application_controller.rb
# encoding: utf-8
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  private

    def set_locale
      I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
      Rails.logger.debug "I18n.locale: #{I18n.locale}"
    end
end

app/helpers/application_helper.rb
# encoding: utf-8
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Uchi
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
  body
    p.notice
      = notice
    p.alert
      = alert
    = yield

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to t('.sign_in'), new_session_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to t('.forgot_your_password'), new_password_path(resource_name)